<?php if (count($errors) > 0) : ?>
    <ul class="alert alert-danger">
        <?php foreach ($errors as $e) : ?>
            <li><?= $e ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<form action="" method="POST">
    <div class="form-group">
        <label for="firstname">Prénom</label>
        <input type="text" class="form-control" value="<?= $prenom ?>" id="firstname" name="firstname">
    </div>
    <div class="form-group">
        <label for="lastname">Nom</label>
        <input type="text" class="form-control" value="<?= $lastname ?>" id="lastname" name="lastname">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" value="<?= $email ?>" id="email" name="email">
    </div>
    <div class="form-group">
        <label for="phone">Téléphone</label>
        <input type="text" class="form-control" value="<?= $phone ?>" id="phone" name="phone">
    </div>
    <button type="submit" class="btn btn-primary">Sauvegarder</button>
</form>
