<h2>Liste des contacts</h2>

<table class="table table-striped">
    <?php foreach ($contacts as $index => $contact) : ?>
        <tr>
            <td><?= $contact['firstname'] ?></td>
            <td><?= $contact['lastname'] ?></td>
            <td><?= $contact['email'] ?></td>
            <td><?= $contact['phone'] ?></td>
            <td><a href="?action=remove&id=<?= $index ?>">Supprimer</a></td>
        </tr>
    <?php endforeach; ?>
</table>
