version: "3"
services:
  blog:
    image: wordpress
    ports:
      - 8000:80
    container_name: wp
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    container_name: mydb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
    command: --default-authentication-plugin=mysql_native_password
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_HOST=mydb
    depends_on:
      - db
