<?php include 'header.phtml' ?>

<div class="container">
    <h1>User Form</h1>

    <form action="" method="post">
        <div class="form-group">
            <label for="email">Email*</label>
            <input type="text" name="email" id="email" class="form-control">
        </div>
        <div class="form-group">
            <label for="password">Mot de passe*</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>
        <div class="form-group">
            <label for="lastname">Nom*</label>
            <input type="text" name="lastname" id="lastname" class="form-control">
        </div>
        <div class="form-group">
            <label for="firstname">Prénom*</label>
            <input type="text" name="firstname" id="firstname" class="form-control">
        </div>
        <button class="btn btn-primary">Sauvegarder</button>
    </form>
</div>

<?php include 'footer.phtml' ?>