<?php include 'header.phtml' ?>

<div class="container">
    <h1 class="mt-2 mb-3">Home Page</h1>

    <a href="add-user.php"class="btn btn-primary mb-3">Ajouter un utilisateur</a>

    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>Email</th>
            <th>First Name</th>
            <th>Last Name</th>
        </tr>
        <?php foreach ($users as $u) : ?>
            <tr>
                <td><?= $u->getId() ?></td>
                <td><?= $u->getEmail() ?></td>
                <td><?= $u->getFirstname() ?></td>
                <td><?= $u->getLastname() ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<?php include 'footer.phtml' ?>