version: "3"
services:
  dbcloud:
    image: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
    command: --default-authentication-plugin=mysql_native_password
  mycloud:
    image: nextcloud
    ports:
      - 9090:80
    restart: always
    depends_on:
      - dbcloud
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8400:80
    environment: 
      - PMA_HOST=dbcloud
    depends_on:
      - dbcloud
